[platformio]
default_envs = promicro_nrf52840

[env:promicro_nrf52840]
platform = platformio/nordicnrf52@10.11.0
board = promicro-nrf52840
framework = arduino
platform_packages =
    platformio/framework-arduinoadafruitnrf52 @ https://github.com/meshtastic/Adafruit_nRF52_Arduino#0fd295f13203e93df19d578073646ec32f2bf45a
    platformio/toolchain-gccarmnoneeabi@~1.90301.0
monitor_speed = 115200
upload_protocol = nrfutil
build_flags =
    -DWEACT_UART_BAUD=115200
    -DWEACT_BLE_NAME_PREFIX=\"WeActPM\"

[env:xiao_nrf52840]
platform = platformio/nordicnrf52@10.11.0
board = xiao_ble
framework = arduino
monitor_speed = 115200
upload_protocol = nrfutil
build_flags =
    -DWEACT_UART_BAUD=115200
    -DWEACT_BLE_NAME_PREFIX=\"WeActPM\"
